// SIGN UP
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const SIGNIN_START = "SIGNIN_START";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";

export const REFRESH_AUTH_START = "REFRESH_AUTH_START";
export const REFRESH_AUTH_SUCCESS = "REFRESH_AUTH_SUCCESS";
export const REFRESH_AUTH_FAILURE = "REFRESH_AUTH_FAILURE";

export const LOG_OUT = "LOG_OUT";

export const ADD_QUESTION_START = "ADD_QUESTION_START";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_QUESTION_FAILURE = "ADD_QUESTION_FAILURE";

export const REFRESH_NOTIFICATION_DATA_START =
	"REFRESH_NOTIFICATION_DATA_START";
export const REFRESH_NOTIFICATION_DATA_SUCCESS =
	"REFRESH_NOTIFICATION_DATA_SUCCESS";
export const REFRESH_NOTIFICATION_DATA_FAILURE =
	"REFRESH_NOTIFICATION_DATA_FAILURE";

export const REFRESH_POSTS_DATA_START = "REFRESH_POSTS_DATA_START";
export const REFRESH_POSTS_DATA_SUCCESS = "REFRESH_POSTS_DATA_SUCCESS";
export const REFRESH_POSTS_DATA_FAILURE = "REFRESH_POSTS_DATA_FAILURE";
