// SIGN UP
export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// SIGN IN
export const SIGNIN_START = "SIGNIN_START";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILURE = "SIGNIN_FAILURE";

// RE AUTHENTICATE USING TOKEN ON REFRESH
export const REFRESH_AUTH_START = "REFRESH_AUTH_START";
export const REFRESH_AUTH_SUCCESS = "REFRESH_AUTH_SUCCESS";
export const REFRESH_AUTH_FAILURE = "REFRESH_AUTH_FAILURE";

// LOG OUT USER
export const LOG_OUT = "LOG_OUT";

// ADD A NEW QUESTION
export const ADD_QUESTION_START = "ADD_QUESTION_START";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_QUESTION_FAILURE = "ADD_QUESTION_FAILURE";

// FETCH ALL USER's NOTIFICATIONS
export const REFRESH_NOTIFICATION_DATA_START =
	"REFRESH_NOTIFICATION_DATA_START";
export const REFRESH_NOTIFICATION_DATA_SUCCESS =
	"REFRESH_NOTIFICATION_DATA_SUCCESS";
export const REFRESH_NOTIFICATION_DATA_FAILURE =
	"REFRESH_NOTIFICATION_DATA_FAILURE";

// FETCH ALL POSTS
export const REFRESH_POSTS_DATA_START = "REFRESH_POSTS_DATA_START";
export const REFRESH_POSTS_DATA_SUCCESS = "REFRESH_POSTS_DATA_SUCCESS";
export const REFRESH_POSTS_DATA_FAILURE = "REFRESH_POSTS_DATA_FAILURE";

// FETCH ALL QUESTIONS
export const FETCH_ALL_QUESTIONS_START = "FETCH_ALL_QUESTIONS_START";
export const FETCH_ALL_QUESTIONS_SUCCESS = "FETCH_ALL_QUESTIONS_SUCCESS";
export const FETCH_ALL_QUESTIONS_FAILURE = "FETCH_ALL_QUESTIONS_FAILURE";

// ADD NEW ANSWER
export const ADD_ANSWER_START = "ADD_ANSWER_START";
export const ADD_ANSWER_SUCCESS = "ADD_ANSWER_SUCCESS";
export const ADD_ANSWER_FAILURE = "ADD_ANSWER_FAILURE";

// CREATE DRAFT
export const CREATE_DRAFT_START = "CREATE_DRAFT_START";
export const CREATE_DRAFT_SUCCESS = "CREATE_DRAFT_SUCCESS";
export const CREATE_DRAFT_FAILURE = "CREATE_DRAFT_FAILURE";

// FETCH ALL DRAFTS
export const FETCH_DRAFTS_START = "FETCH_DRAFTS_START";
export const FETCH_DRAFTS_SUCCESS = "FETCH_DRAFTS_SUCCESS";
export const FETCH_DRAFTS_FAILURE = "FETCH_DRAFTS_FAILURE";
